services:
  yourlifetasks.application:
    image: yourlifetasks.application
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: YourLifeTasks.Application/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DbSettings__Server: db
      DbSettings__Username: postgres
      DbSettings__Password: postgres
      DbSettings__Database: your-life-tasks-db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: your-life-tasks-db
    restart: always
    user: postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
