services:
  yourlifetasks.application:
    image: yourlifetasks.application
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: YourLifeTasks.Application/Dockerfile
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: chernykhav
      POSTGRES_PASSWORD: chernykhav
      POSTGRES_DB: your-life-tasks-db
    restart: always
